import com.sample.candidate.Candidate
import com.sample.candidate.Skill
import com.sample.candidate.TestScore
import com.sample.candidate.InterviewScore
import com.sample.candidate.ProjectScore

rule "Schedule For Testing"
when
	$candidate: Candidate(status=='Submitted', yrsExperience >= 10, 
		(skill.name=='Java' && skill.yrsExperience>=5) || (skill.name=='C#' && skill.yrsExperience>=5))
then
	$candidate.setStatus('Testing');
end

rule "Schedule For Project"
when
	$candidate: Candidate(status=='Interview', 	(interviewScore.speakExperience>.9 && interviewScore.problemSolving>.8 && interviewScore.communication>.9) );
then
	$candidate.setStatus('Project');
end

rule "Schedule For Hiring"
when
	$candidate: Candidate(status=='Project', (projectScore.completeness>.8 && projectScore.architecture>.9 && projectScore.gui>.7) );
then
	$candidate.setStatus('Hiring');
end